/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface Payment { 
    id?: number;
    version?: number;
    createdBy?: string;
    updatedBy?: string;
    stockId?: number;
    amountAvailable?: number;
    amountReserved?: number;
    amount?: number;
    status?: Payment.StatusEnum;
    transactionDate?: string;
}
export namespace Payment {
    export type StatusEnum = 'NEW' | 'ACCEPT' | 'REJECT' | 'CONFIRMED' | 'ROLLBACK';
    export const StatusEnum = {
        New: 'NEW' as StatusEnum,
        Accept: 'ACCEPT' as StatusEnum,
        Reject: 'REJECT' as StatusEnum,
        Confirmed: 'CONFIRMED' as StatusEnum,
        Rollback: 'ROLLBACK' as StatusEnum
    };
}


