server:
  host: localhost
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${server.host}:${server.port}/eureka

spring:
  application:
    name: discovery-server
  banner:
    location: banner.txt
  config:
    import: info.yml