version: '3.3'

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_kyc_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak
    expose:
      - "54322"
    ports:
      - "54322:54322"
    volumes: 
      - product-volume:/var/lib/postgresql/data
    command: -p 54322
    
volumes:
  product-volume:
    driver: local