version: '3'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: keycloak_oauth
      ports:
        - 8043:8080
        - 8443:8443
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: 192.168.1.21:5432
        #DB_ADDR: 10.10.28.13:5432
        DB_DATABASE: keycloak_db
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: postgres
        KEYCLOAK_USER: admin_keycloak
        KEYCLOAK_PASSWORD: 123456
        KEYCLOAK_FRONTEND_URL: http://localhost:8043/auth
