server:
  host: localhost
  port: 8085
  gateway: http://${server.host}:${server.port}

keycloak:
  host: http://${server.host}:8043/auth
  realm: food-microservice
  resource: food-microservice-backend
  secret: bQWQTn5RAfDSsXPG8ko7AsEnqsW7hbmj
  url: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${server.host}:8761/eureka

spring:
  application:
    name: gateway-service
  banner:
    location: banner.txt
  config:
    import: info.yml,predicate.yml,openapi.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${server.host}:8043/auth/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#  api-docs:
#    path: /v3/api-docs

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username