server:
  host: localhost
  port: 8085

  food: http://${server.host}:8081
  user: http://${server.host}:8082
  logs: http://${server.host}:8086
  stock: http://${server.host}:8087
  payment: http://${server.host}:8088
  gateway: http://${server.host}:${server.port}

keycloak:
  host: http://${server.host}:8043/auth
  realm: food-microservice
  resource: food-microservice-backend
  secret: bQWQTn5RAfDSsXPG8ko7AsEnqsW7hbmj
  url: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${server.host}:8761/eureka/

spring:
  application:
    name: api-gateway
  banner:
    location: banner.txt
  config:
    import: info.yml,predicate.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${server.host}:8043/auth/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs


#springdoc:
#  enable-native-support: true
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
#        primaryName: API Gateway Service
#      - url: /food-service/v3/api-docs/foods
#        name: Food Service
#        primaryName: Food Service
#      #      - url: /user-service/v3/api-docs
#      - url: ${server.user}/v3/api-docs
#        name: User Service
#        primaryName: User Service


jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username