server:
  host: localhost
  port: 8085

keycloak:
  host: http://${server.host}:8043/auth
  realm: food-microservice
  resource: food-microservice-backend
  secret: bQWQTn5RAfDSsXPG8ko7AsEnqsW7hbmj
  url: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${server.host}:8761/eureka/

spring:
  application:
    name: api-gateway
  #  main:
  #    web-application-type: reactive
  #    allow-bean-definition-overriding: true
  banner:
    location: banner.txt
  config:
    import: info.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${server.host}:8043/auth/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8082
#          uri: lb://user-service
          predicates:
            - Path=/api/**

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username