server:
  host: 127.0.0.1
  port: 8085

keycloak:
  host: http://${server.host}}:8043/auth
  realm: food-microservice
  resource: food-microservice-backend
  secret: 8It8vOmZU0iAWEJGbEgowvUaQWSSH523
  url: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/token

spring:
  application:
    name: api-gateway
  banner:
    location: banner.txt
  config:
    import: info.properties,eureka.properties,predicate.properties
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}