server:
  host: localhost
  port: 8085

keycloak:
  host: http://${server.host}:8043/auth
  realm: food-microservice
  resource: food-microservice-backend
  secret: bQWQTn5RAfDSsXPG8ko7AsEnqsW7hbmj
  url: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/token

spring:
  application:
    name: api-gateway
  banner:
    location: banner.txt
  config:
    import: info.yml,eureka.yml,predicate.properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${server.host}:8043/auth/realms/${keycloak.realm}
          jwk-set-uri: http://${server.host}:8043/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principal-attribute: preferred_username

openapi:
  oAuthFlow:
    tokenUrl: http://localhost:9000/realms/${keycloak.realm}/protocol/openid-connect/token