spring:
  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: food-service
          order: 0
          uri: ${server.food}
          predicates:
            - Host=**
            - Path=/api/foods/**

        - id: user-service
          order: 1
          uri: ${server.user}
          predicates:
            - Host=**
            - Path=/api/users/**