spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: foods
          order: 0
          uri: lb://food-service
          predicates:
            - Host=**
            - Path=/api/foods/**
          filters:
            - FoodFilter

        - id: stocks
          order: 1
          uri: lb://stock-service
          predicates:
            - Host=**
            - Path=/api/stocks/**
          filters:
            - StockFilter

        - id: payments
          order: 2
          uri: lb://payment-service
          predicates:
            - Host=**
            - Path=/api/payments/**
          filters:
            - PaymentFilter

        - id: logs
          order: 3
          uri: lb://log-service
          predicates:
            - Host=**
            - Path=/api/logs/**

        - id: gateways
          order: 4
          uri: lb://gateway-service
          predicates:
            - Host=**
            - Path=/api/auths/**
          filters:
            - PaymentFilter