spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: foods
          order: 0
          uri: lb://food-service
          predicates:
            - Host=**
            - Path=/api/foods/**

        - id: users
          order: 1
          uri: lb://user-service
          predicates:
            - Host=**
            - Path=/api/users/**

        - id: stocks
          order: 2
          uri: lb://stock-service
          predicates:
            - Host=**
            - Path=/api/stocks/**

        - id: payments
          order: 3
          uri: lb://payment-service
          predicates:
            - Host=**
            - Path=/api/payments/**

        - id: logs
          order: 4
          uri: lb://log-service
          predicates:
            - Host=**
            - Path=/api/logs/**

        - id: gateways
          order: 5
          uri: ${server.gateway}
          predicates:
            - Host=**
            - Path=/v3/api-docs