spring:
  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
      routes:
        - id: foods-service
          order: 0
          uri: ${server.food}
          predicates:
            - Host=**
            - Path=/api/foods/**

        - id: users-service
          order: 1
          uri: ${server.user}
          predicates:
            - Host=**
            - Path=/api/users/**

        - id: stocks-service
          order: 2
          uri: ${server.stock}
          predicates:
            - Host=**
            - Path=/api/stocks/**

        - id: payments-service
          order: 3
          uri: ${server.payment}
          predicates:
            - Host=**
            - Path=/api/payments/**

        - id: logs-service
          order: 4
          uri: ${server.logs}
          predicates:
            - Host=**
            - Path=/api/logs/**

        - id: gateways-service
          order: 5
          uri: ${server.gateway}
          predicates:
            - Host=**
            - Path=/v3/api-docs