spring:
  rabbitmq:
    host: ${server.host}
    port: 5672
    username: rabbit
    password: rabbit

##queue##
rabbit:
  queue: food_queue
  queue_json: food_queue_json
  exchange: rabbit_exchange
  routing: rabbit_routing_key
  routing_json: rabbit_routing_json_key