/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialRepresentationConfig } from './credentialRepresentationConfig';


/**
 * 
 */
export interface CredentialRepresentation { 
    id?: string;
    type?: string;
    userLabel?: string;
    createdDate?: number;
    secretData?: string;
    credentialData?: string;
    priority?: number;
    value?: string;
    temporary?: boolean;
    device?: string;
    hashedSaltedValue?: string;
    salt?: string;
    hashIterations?: number;
    counter?: number;
    algorithm?: string;
    digits?: number;
    period?: number;
    config?: CredentialRepresentationConfig;
}

