/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialRepresentation } from './credentialRepresentation';
import { SocialLinkRepresentation } from './socialLinkRepresentation';
import { FederatedIdentityRepresentation } from './federatedIdentityRepresentation';
import { UserConsentRepresentation } from './userConsentRepresentation';


/**
 * 
 */
export interface UserRepresentation { 
    self?: string;
    id?: string;
    origin?: string;
    createdTimestamp?: number;
    username?: string;
    enabled?: boolean;
    totp?: boolean;
    emailVerified?: boolean;
    firstName?: string;
    lastName?: string;
    email?: string;
    federationLink?: string;
    serviceAccountClientId?: string;
    attributes?: { [key: string]: Array<string>; };
    credentials?: Array<CredentialRepresentation>;
    disableableCredentialTypes?: Set<string>;
    requiredActions?: Array<string>;
    federatedIdentities?: Array<FederatedIdentityRepresentation>;
    realmRoles?: Array<string>;
    clientRoles?: { [key: string]: Array<string>; };
    clientConsents?: Array<UserConsentRepresentation>;
    notBefore?: number;
    applicationRoles?: { [key: string]: Array<string>; };
    socialLinks?: Array<SocialLinkRepresentation>;
    groups?: Array<string>;
    access?: { [key: string]: boolean; };
}

