/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsUserDepartmentJoinListValueParentFetchesInner } from './dataSourceLoadOptionsUserDepartmentJoinListValueParentFetchesInner';
import { DataSourceLoadOptionsUserDepartmentJoinListValueOn } from './dataSourceLoadOptionsUserDepartmentJoinListValueOn';
import { DataSourceLoadOptionsUserDepartmentJoinListValueParentModel } from './dataSourceLoadOptionsUserDepartmentJoinListValueParentModel';
import { DataSourceLoadOptionsUserDepartmentJoinListValueParentFetchesInnerAttribute } from './dataSourceLoadOptionsUserDepartmentJoinListValueParentFetchesInnerAttribute';
import { DataSourceLoadOptionsUserDepartmentJoinListValueParent } from './dataSourceLoadOptionsUserDepartmentJoinListValueParent';
import { DataSourceLoadOptionsUserDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsUserDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsUserDepartmentJoinListValueParentParentPath } from './dataSourceLoadOptionsUserDepartmentJoinListValueParentParentPath';


export interface DataSourceLoadOptionsUserDepartmentJoinListValue { 
    parent?: DataSourceLoadOptionsUserDepartmentJoinListValueParent;
    attribute?: DataSourceLoadOptionsUserDepartmentJoinListValueParentFetchesInnerAttribute;
    on?: DataSourceLoadOptionsUserDepartmentJoinListValueOn;
    joinType?: DataSourceLoadOptionsUserDepartmentJoinListValue.JoinTypeEnum;
    correlationParent?: DataSourceLoadOptionsUserDepartmentJoinListValueParent;
    correlated?: boolean;
    model?: DataSourceLoadOptionsUserDepartmentJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsUserDepartmentJoinListValueParentParentPath;
    compoundSelection?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsUserDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner>;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsUserDepartmentJoinListValueParentFetchesInner>;
}
export namespace DataSourceLoadOptionsUserDepartmentJoinListValue {
    export type JoinTypeEnum = 'INNER' | 'LEFT' | 'RIGHT';
    export const JoinTypeEnum = {
        Inner: 'INNER' as JoinTypeEnum,
        Left: 'LEFT' as JoinTypeEnum,
        Right: 'RIGHT' as JoinTypeEnum
    };
}


