/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsDepartmentJoinListValueParentModel } from './dataSourceLoadOptionsDepartmentJoinListValueParentModel';
import { DataSourceLoadOptionsDepartmentJoinListValueParentParentPath } from './dataSourceLoadOptionsDepartmentJoinListValueParentParentPath';
import { DataSourceLoadOptionsDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsDepartmentJoinListValueParentFetchesInner } from './dataSourceLoadOptionsDepartmentJoinListValueParentFetchesInner';


export interface DataSourceLoadOptionsDepartmentJoinListValueParent { 
    correlated?: boolean;
    model?: DataSourceLoadOptionsDepartmentJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsDepartmentJoinListValueParentParentPath;
    compoundSelection?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner>;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsDepartmentJoinListValueParentFetchesInner>;
}

