/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsUserDepartmentJoinListValueOnExpressionsInner } from './dataSourceLoadOptionsUserDepartmentJoinListValueOnExpressionsInner';
import { DataSourceLoadOptionsUserDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsUserDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner';


export interface DataSourceLoadOptionsUserDepartmentJoinListValueOn { 
    expressions?: Array<DataSourceLoadOptionsUserDepartmentJoinListValueOnExpressionsInner>;
    operator?: DataSourceLoadOptionsUserDepartmentJoinListValueOn.OperatorEnum;
    negated?: boolean;
    compoundSelection?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsUserDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner>;
    alias?: string;
}
export namespace DataSourceLoadOptionsUserDepartmentJoinListValueOn {
    export type OperatorEnum = 'AND' | 'OR';
    export const OperatorEnum = {
        And: 'AND' as OperatorEnum,
        Or: 'OR' as OperatorEnum
    };
}


