/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsDepartmentJoinListValueOn } from './dataSourceLoadOptionsDepartmentJoinListValueOn';
import { DataSourceLoadOptionsDepartmentJoinListValueParentModel } from './dataSourceLoadOptionsDepartmentJoinListValueParentModel';
import { DataSourceLoadOptionsDepartmentJoinListValueParent } from './dataSourceLoadOptionsDepartmentJoinListValueParent';
import { DataSourceLoadOptionsDepartmentJoinListValueParentParentPath } from './dataSourceLoadOptionsDepartmentJoinListValueParentParentPath';
import { DataSourceLoadOptionsDepartmentJoinListValueParentFetchesInnerAttribute } from './dataSourceLoadOptionsDepartmentJoinListValueParentFetchesInnerAttribute';
import { DataSourceLoadOptionsDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsDepartmentJoinListValueParentFetchesInner } from './dataSourceLoadOptionsDepartmentJoinListValueParentFetchesInner';


export interface DataSourceLoadOptionsDepartmentJoinListValue { 
    parent?: DataSourceLoadOptionsDepartmentJoinListValueParent;
    attribute?: DataSourceLoadOptionsDepartmentJoinListValueParentFetchesInnerAttribute;
    joinType?: DataSourceLoadOptionsDepartmentJoinListValue.JoinTypeEnum;
    on?: DataSourceLoadOptionsDepartmentJoinListValueOn;
    correlationParent?: DataSourceLoadOptionsDepartmentJoinListValueParent;
    correlated?: boolean;
    model?: DataSourceLoadOptionsDepartmentJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsDepartmentJoinListValueParentParentPath;
    compoundSelection?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsDepartmentJoinListValueParentParentPathCompoundSelectionItemsInner>;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsDepartmentJoinListValueParentFetchesInner>;
}
export namespace DataSourceLoadOptionsDepartmentJoinListValue {
    export type JoinTypeEnum = 'INNER' | 'LEFT' | 'RIGHT';
    export const JoinTypeEnum = {
        Inner: 'INNER' as JoinTypeEnum,
        Left: 'LEFT' as JoinTypeEnum,
        Right: 'RIGHT' as JoinTypeEnum
    };
}


