/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDepartment } from './userDepartment';
import { LoadResultGroup } from './loadResultGroup';


/**
 * 
 */
export interface LoadResultUserDepartment { 
    data?: Array<UserDepartment>;
    totalCount?: number;
    groupData?: Array<LoadResultGroup>;
    groupCount?: number;
    success?: boolean;
    errorId?: number;
    result?: Array<UserDepartment>;
}

