/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredPluralAttributesInner } from './dataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredPluralAttributesInner';
import { DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredSingularAttributesInner } from './dataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredSingularAttributesInner';
import { DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeAttributesInner } from './dataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeAttributesInner';


export interface DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringType { 
    attributes?: Set<DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeAttributesInner>;
    declaredPluralAttributes?: Set<DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredPluralAttributesInner>;
    declaredSingularAttributes?: Set<DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredSingularAttributesInner>;
    declaredAttributes?: Set<DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeAttributesInner>;
    singularAttributes?: Set<DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredSingularAttributesInner>;
    pluralAttributes?: Set<DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringTypeDeclaredPluralAttributesInner>;
    persistenceType?: DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringType.PersistenceTypeEnum;
}
export namespace DataSourceLoadOptionsOrdersJoinListValueParentFetchesInnerAttributeDeclaringType {
    export type PersistenceTypeEnum = 'ENTITY' | 'EMBEDDABLE' | 'MAPPED_SUPERCLASS' | 'BASIC';
    export const PersistenceTypeEnum = {
        Entity: 'ENTITY' as PersistenceTypeEnum,
        Embeddable: 'EMBEDDABLE' as PersistenceTypeEnum,
        MappedSuperclass: 'MAPPED_SUPERCLASS' as PersistenceTypeEnum,
        Basic: 'BASIC' as PersistenceTypeEnum
    };
}


