/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsOrdersJoinListValueParentParentPath } from './dataSourceLoadOptionsOrdersJoinListValueParentParentPath';
import { DataSourceLoadOptionsOrdersJoinListValueParentModel } from './dataSourceLoadOptionsOrdersJoinListValueParentModel';
import { DataSourceLoadOptionsOrdersJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsOrdersJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsOrdersJoinListValueParentFetchesInner } from './dataSourceLoadOptionsOrdersJoinListValueParentFetchesInner';


export interface DataSourceLoadOptionsOrdersJoinListValueParent { 
    correlated?: boolean;
    model?: DataSourceLoadOptionsOrdersJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsOrdersJoinListValueParentParentPath;
    compoundSelectionItems?: Array<DataSourceLoadOptionsOrdersJoinListValueParentParentPathCompoundSelectionItemsInner>;
    compoundSelection?: boolean;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsOrdersJoinListValueParentFetchesInner>;
}

