/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsOrdersJoinListValueOnExpressionsInner } from './dataSourceLoadOptionsOrdersJoinListValueOnExpressionsInner';
import { DataSourceLoadOptionsOrdersJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsOrdersJoinListValueParentParentPathCompoundSelectionItemsInner';


export interface DataSourceLoadOptionsOrdersJoinListValueOn { 
    expressions?: Array<DataSourceLoadOptionsOrdersJoinListValueOnExpressionsInner>;
    operator?: DataSourceLoadOptionsOrdersJoinListValueOn.OperatorEnum;
    negated?: boolean;
    compoundSelection?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsOrdersJoinListValueParentParentPathCompoundSelectionItemsInner>;
    alias?: string;
}
export namespace DataSourceLoadOptionsOrdersJoinListValueOn {
    export type OperatorEnum = 'AND' | 'OR';
    export const OperatorEnum = {
        And: 'AND' as OperatorEnum,
        Or: 'OR' as OperatorEnum
    };
}


