/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsFoodJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsFoodJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsFoodJoinListValueParentFetchesInner } from './dataSourceLoadOptionsFoodJoinListValueParentFetchesInner';
import { DataSourceLoadOptionsFoodJoinListValueParentParentPath } from './dataSourceLoadOptionsFoodJoinListValueParentParentPath';
import { DataSourceLoadOptionsFoodJoinListValueParentModel } from './dataSourceLoadOptionsFoodJoinListValueParentModel';


export interface DataSourceLoadOptionsFoodJoinListValueParent { 
    correlated?: boolean;
    model?: DataSourceLoadOptionsFoodJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsFoodJoinListValueParentParentPath;
    compoundSelectionItems?: Array<DataSourceLoadOptionsFoodJoinListValueParentParentPathCompoundSelectionItemsInner>;
    compoundSelection?: boolean;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsFoodJoinListValueParentFetchesInner>;
}

