/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Food } from './food';


/**
 * 
 */
export interface Orders { 
    id?: number;
    food?: Food;
    stockId?: number;
    paymentId?: number;
    price?: number;
    totalPrice?: number;
    status?: Orders.StatusEnum;
    createDate?: string;
    orderDate?: string;
    image?: string;
}
export namespace Orders {
    export type StatusEnum = 'BASKET' | 'ACCEPT' | 'REJECT';
    export const StatusEnum = {
        Basket: 'BASKET' as StatusEnum,
        Accept: 'ACCEPT' as StatusEnum,
        Reject: 'REJECT' as StatusEnum
    };
}


