server:
  host: 127.0.0.1
  port: 8082
  db: food_user_db

eureka:
  client:
    service-url:
      defaultZone: http://${server.host}:8761/eureka/

spring:
  application:
    name: user-service
  banner:
    location: banner.txt
  config:
    import: info.yml,rabbit.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${server.host}:5432/${server.db}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update