/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsPaymentJoinListValueParentParentPath } from './dataSourceLoadOptionsPaymentJoinListValueParentParentPath';
import { DataSourceLoadOptionsPaymentJoinListValueParentFetchesInner } from './dataSourceLoadOptionsPaymentJoinListValueParentFetchesInner';
import { DataSourceLoadOptionsPaymentJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsPaymentJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsPaymentJoinListValueParentModel } from './dataSourceLoadOptionsPaymentJoinListValueParentModel';


export interface DataSourceLoadOptionsPaymentJoinListValueParent { 
    correlated?: boolean;
    model?: DataSourceLoadOptionsPaymentJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsPaymentJoinListValueParentParentPath;
    compoundSelectionItems?: Array<DataSourceLoadOptionsPaymentJoinListValueParentParentPathCompoundSelectionItemsInner>;
    compoundSelection?: boolean;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsPaymentJoinListValueParentFetchesInner>;
}

