/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsPaymentJoinListValueParentFetchesInnerAttribute } from './dataSourceLoadOptionsPaymentJoinListValueParentFetchesInnerAttribute';
import { DataSourceLoadOptionsPaymentJoinListValueParentParentPath } from './dataSourceLoadOptionsPaymentJoinListValueParentParentPath';
import { DataSourceLoadOptionsPaymentJoinListValueParentFetchesInner } from './dataSourceLoadOptionsPaymentJoinListValueParentFetchesInner';
import { DataSourceLoadOptionsPaymentJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsPaymentJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsPaymentJoinListValueOn } from './dataSourceLoadOptionsPaymentJoinListValueOn';
import { DataSourceLoadOptionsPaymentJoinListValueParentModel } from './dataSourceLoadOptionsPaymentJoinListValueParentModel';
import { DataSourceLoadOptionsPaymentJoinListValueParent } from './dataSourceLoadOptionsPaymentJoinListValueParent';


export interface DataSourceLoadOptionsPaymentJoinListValue { 
    parent?: DataSourceLoadOptionsPaymentJoinListValueParent;
    attribute?: DataSourceLoadOptionsPaymentJoinListValueParentFetchesInnerAttribute;
    on?: DataSourceLoadOptionsPaymentJoinListValueOn;
    joinType?: DataSourceLoadOptionsPaymentJoinListValue.JoinTypeEnum;
    correlated?: boolean;
    correlationParent?: DataSourceLoadOptionsPaymentJoinListValueParent;
    model?: DataSourceLoadOptionsPaymentJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsPaymentJoinListValueParentParentPath;
    compoundSelectionItems?: Array<DataSourceLoadOptionsPaymentJoinListValueParentParentPathCompoundSelectionItemsInner>;
    compoundSelection?: boolean;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsPaymentJoinListValueParentFetchesInner>;
}
export namespace DataSourceLoadOptionsPaymentJoinListValue {
    export type JoinTypeEnum = 'INNER' | 'LEFT' | 'RIGHT';
    export const JoinTypeEnum = {
        Inner: 'INNER' as JoinTypeEnum,
        Left: 'LEFT' as JoinTypeEnum,
        Right: 'RIGHT' as JoinTypeEnum
    };
}


