version: '3.3'

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9094"
    container_name: minio_api
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9001:9001'
      - '9094:9094'
    volumes: 
      - ~/minio/data:/data

volumes:
  minio:
    driver: local