server:
  host: 127.0.0.1
  port: 8081
  db: food_postgis_db

spring:
  application:
    name: food-service
  banner:
    location: banner.txt
  config:
    import: eureka.yml,info.yml,kafka.yml,minio.yml
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: com.food.dialect.PostgresSQL94JsonDialect
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql_postGIS://${server.host}:5433/${server.db}
    username: postgis
    password: postgis
    driver-class-name: org.postgis.DriverWrapper
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 2000000
      connection-timeout: 60000
      pool-name: foodConnectionPool

grpc:
  client:
    grpc-stock-service:
      address: static://${server.host}:9090
      negotiation-type: plaintext
    grpc-payment-service:
      address: static://${server.host}:9091
      negotiation-type: plaintext
