server:
  host: 127.0.0.1
  port: 8087
  db: food_stock_db

spring:
  application:
    name: stock-service
  banner:
    location: banner.txt
  config:
    import: eureka.yml,info.yml,kafka.yml,quartz.yml
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: com.food.dialect.PostgresSQL94JsonDialect
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://${server.host}:5432/${server.db}
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 2000000
      connection-timeout: 60000
      pool-name: stockConnectionPool

grpc:
  server:
    port: 9090
