version: '3.3'

services:
  postgis:
    image: postgis/postgis
    container_name: postgis_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_DB=food_postgis_db
      - POSTGRES_USER=postgis
    ports:
      - '5433:5432'
    volumes: 
      - postgis-data:/var/lib/postgresql

volumes:
  postgis-data:
    driver: local