/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsStockJoinListValueOnExpressionsInner } from './dataSourceLoadOptionsStockJoinListValueOnExpressionsInner';
import { DataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner';


export interface DataSourceLoadOptionsStockJoinListValueOn { 
    expressions?: Array<DataSourceLoadOptionsStockJoinListValueOnExpressionsInner>;
    operator?: DataSourceLoadOptionsStockJoinListValueOn.OperatorEnum;
    negated?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner>;
    compoundSelection?: boolean;
    alias?: string;
}
export namespace DataSourceLoadOptionsStockJoinListValueOn {
    export type OperatorEnum = 'AND' | 'OR';
    export const OperatorEnum = {
        And: 'AND' as OperatorEnum,
        Or: 'OR' as OperatorEnum
    };
}


