/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsStockJoinListValueParentModel } from './dataSourceLoadOptionsStockJoinListValueParentModel';
import { DataSourceLoadOptionsStockJoinListValueParentParentPath } from './dataSourceLoadOptionsStockJoinListValueParentParentPath';
import { DataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsStockJoinListValueParentFetchesInner } from './dataSourceLoadOptionsStockJoinListValueParentFetchesInner';


export interface DataSourceLoadOptionsStockJoinListValueParent { 
    correlated?: boolean;
    model?: DataSourceLoadOptionsStockJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsStockJoinListValueParentParentPath;
    compoundSelection?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner>;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsStockJoinListValueParentFetchesInner>;
}

