/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataSourceLoadOptionsStockJoinListValueParentModel { 
    bindableType?: DataSourceLoadOptionsStockJoinListValueParentModel.BindableTypeEnum;
}
export namespace DataSourceLoadOptionsStockJoinListValueParentModel {
    export type BindableTypeEnum = 'SINGULAR_ATTRIBUTE' | 'PLURAL_ATTRIBUTE' | 'ENTITY_TYPE';
    export const BindableTypeEnum = {
        SingularAttribute: 'SINGULAR_ATTRIBUTE' as BindableTypeEnum,
        PluralAttribute: 'PLURAL_ATTRIBUTE' as BindableTypeEnum,
        EntityType: 'ENTITY_TYPE' as BindableTypeEnum
    };
}


