/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceLoadOptionsStockJoinListValueOn } from './dataSourceLoadOptionsStockJoinListValueOn';
import { DataSourceLoadOptionsStockJoinListValueParentModel } from './dataSourceLoadOptionsStockJoinListValueParentModel';
import { DataSourceLoadOptionsStockJoinListValueParentParentPath } from './dataSourceLoadOptionsStockJoinListValueParentParentPath';
import { DataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner } from './dataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner';
import { DataSourceLoadOptionsStockJoinListValueParentFetchesInner } from './dataSourceLoadOptionsStockJoinListValueParentFetchesInner';
import { DataSourceLoadOptionsStockJoinListValueParent } from './dataSourceLoadOptionsStockJoinListValueParent';
import { DataSourceLoadOptionsStockJoinListValueParentFetchesInnerAttribute } from './dataSourceLoadOptionsStockJoinListValueParentFetchesInnerAttribute';


export interface DataSourceLoadOptionsStockJoinListValue { 
    parent?: DataSourceLoadOptionsStockJoinListValueParent;
    attribute?: DataSourceLoadOptionsStockJoinListValueParentFetchesInnerAttribute;
    joinType?: DataSourceLoadOptionsStockJoinListValue.JoinTypeEnum;
    on?: DataSourceLoadOptionsStockJoinListValueOn;
    correlated?: boolean;
    correlationParent?: DataSourceLoadOptionsStockJoinListValueParent;
    model?: DataSourceLoadOptionsStockJoinListValueParentModel;
    parentPath?: DataSourceLoadOptionsStockJoinListValueParentParentPath;
    compoundSelection?: boolean;
    compoundSelectionItems?: Array<DataSourceLoadOptionsStockJoinListValueParentParentPathCompoundSelectionItemsInner>;
    alias?: string;
    fetches?: Set<DataSourceLoadOptionsStockJoinListValueParentFetchesInner>;
}
export namespace DataSourceLoadOptionsStockJoinListValue {
    export type JoinTypeEnum = 'INNER' | 'LEFT' | 'RIGHT';
    export const JoinTypeEnum = {
        Inner: 'INNER' as JoinTypeEnum,
        Left: 'LEFT' as JoinTypeEnum,
        Right: 'RIGHT' as JoinTypeEnum
    };
}


