/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupingInfo } from './groupingInfo';
import { SortingInfo } from './sortingInfo';
import { SummaryInfo } from './summaryInfo';


/**
 * 
 */
export interface DataSourceLoadOptions { 
    requireTotalCount?: boolean;
    requireGroupCount?: boolean;
    skip?: number;
    take?: number;
    sort?: Array<SortingInfo>;
    group?: Array<GroupingInfo>;
    filter?: Array<object>;
    totalSummary?: Array<SummaryInfo>;
    groupSummary?: Array<SummaryInfo>;
    select?: Array<string>;
    preSelect?: Array<string>;
    remoteSelect?: boolean;
    remoteGrouping?: boolean;
    expandLinqSumType?: boolean;
    primaryKey?: Array<string>;
    defaultSort?: string;
    stringToLower?: boolean;
    paginateViaPrimaryKey?: boolean;
    sortByPrimaryKey?: boolean;
    allowAsyncOverSync?: boolean;
    searchOperation?: string;
    searchValue?: string;
    searchExpr?: object;
    userData?: object;
    distinct?: boolean;
    countQuery?: boolean;
    summaryQuery?: boolean;
}

