/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface Stock { 
    id?: number;
    version?: number;
    createdBy?: string;
    updatedBy?: string;
    name?: string;
    price?: number;
    availableItems?: number;
    reservedItems?: number;
    unit?: Stock.UnitEnum;
    status?: Stock.StatusEnum;
    transactionDate?: string;
}
export namespace Stock {
    export type UnitEnum = 'Adet' | 'Kilogram' | 'Gram' | 'Ton' | 'Litre' | 'Metre' | 'Santimetre';
    export const UnitEnum = {
        Adet: 'Adet' as UnitEnum,
        Kilogram: 'Kilogram' as UnitEnum,
        Gram: 'Gram' as UnitEnum,
        Ton: 'Ton' as UnitEnum,
        Litre: 'Litre' as UnitEnum,
        Metre: 'Metre' as UnitEnum,
        Santimetre: 'Santimetre' as UnitEnum
    };
    export type StatusEnum = 'NEW' | 'ACCEPT' | 'REJECT' | 'CONFIRMED' | 'ROLLBACK';
    export const StatusEnum = {
        New: 'NEW' as StatusEnum,
        Accept: 'ACCEPT' as StatusEnum,
        Reject: 'REJECT' as StatusEnum,
        Confirmed: 'CONFIRMED' as StatusEnum,
        Rollback: 'ROLLBACK' as StatusEnum
    };
}


