/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface Stock { 
    version?: number;
    createdBy?: string;
    updatedBy?: string;
    stockId?: string;
    foodId?: string;
    price?: number;
    availableItems?: number;
    reservedItems?: number;
    description?: string;
    status?: string;
    transactionDate?: string;
}

