/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface StockDto { 
    stockId?: string;
    foodId?: string;
    price?: number;
    description?: string;
    status?: StockDto.StatusEnum;
    availableItems?: number;
    reservedItems?: number;
    transactionDate?: string;
}
export namespace StockDto {
    export type StatusEnum = 'NEW' | 'ACCEPT' | 'REJECT' | 'CONFIRMED' | 'ROLLBACK';
    export const StatusEnum = {
        New: 'NEW' as StatusEnum,
        Accept: 'ACCEPT' as StatusEnum,
        Reject: 'REJECT' as StatusEnum,
        Confirmed: 'CONFIRMED' as StatusEnum,
        Rollback: 'ROLLBACK' as StatusEnum
    };
}


